language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
  # TEST_TYPE:
  #        1 : Check if this PR works with current downstream package
  #        2 : Check if this PR works with 315.1.10
env:
  global:
    - secure: "RBAgRKTb2SEKlEcylwZNJdE0hDETvICOPT2onYKsye/GvGTqBh/v3OumB1Fs9ApJ6iajWXS7Sr0gP2kfDUHjZ8t7sLUHZ/PFZqvEgNCGwxhGaCTMQOLTU3N0a5Dw8dRUVwYqnyCEfrFrPkpeCvEJe4h+N/HCPA6SL4KoUzhbdT0="
  matrix:
    - TEST_PACKAGE=hrpsys
    - TEST_TYPE=iob         TEST_PACKAGE=hrpsys
    - TEST_TYPE=stable_rtc  TEST_PACKAGE=hrpsys
    - TEST_TYPE=work_with_downstream  TEST_PACKAGE=hrpsys-tools
    - TEST_TYPE=work_with_315_1_10    TEST_PACKAGE=hrpsys-tools
    - TEST_TYPE=work_with_downstream  TEST_PACKAGE=hrpsys-ros-bridge
    - TEST_TYPE=work_with_315_1_10    TEST_PACKAGE=hrpsys-ros-bridge
    - TEST_TYPE=work_with_downstream  TEST_PACKAGE=hironx-ros-bridge
    - TEST_TYPE=work_with_315_1_10    TEST_PACKAGE=hironx-ros-bridge
script: source .travis.sh
after_success:
  - set +x
  - export GIT_COMMITTER_NAME=$GIT_NAME
  - export GIT_COMMITTER_EMAIL=$GIT_EMAIL
  - export GIT_AUTHOR_NAME=$GIT_NAME
  - export GIT_AUTHOR_EMAIL=$GIT_EMAIL
  - if [ "$TRAVIS_BRANCH" == "gendoc" -a "$TEST_PACKAGE" == "hrpsys" -a "$TEST_TYPE" == "" ]; then cd ~/;            fi
  - if [ "$TRAVIS_BRANCH" == "gendoc" -a "$TEST_PACKAGE" == "hrpsys" -a "$TEST_TYPE" == "" ]; then git clone --branch gh-pages https://github.com/$TRAVIS_REPO_SLUG doc;  fi
  - if [ "$TRAVIS_BRANCH" == "gendoc" -a "$TEST_PACKAGE" == "hrpsys" -a "$TEST_TYPE" == "" ]; then cd doc;           fi
  - if [ "$TRAVIS_BRANCH" == "gendoc" -a "$TEST_PACKAGE" == "hrpsys" -a "$TEST_TYPE" == "" ]; then cp -r ~/build/doc/html/* ./; fi
  - if [ "$TRAVIS_BRANCH" == "gendoc" -a "$TEST_PACKAGE" == "hrpsys" -a "$TEST_TYPE" == "" ]; then git status;                  fi
  - if [ "$TRAVIS_BRANCH" == "gendoc" -a "$TEST_PACKAGE" == "hrpsys" -a "$TEST_TYPE" == "" ]; then git add -f .;                  fi
  - if [ "$TRAVIS_BRANCH" == "gendoc" -a "$TEST_PACKAGE" == "hrpsys" -a "$TEST_TYPE" == "" ]; then git commit -m "Build documents from $TRAVIS_COMMIT" . ; fi
  - if [ "$TRAVIS_BRANCH" == "gendoc" -a "$TEST_PACKAGE" == "hrpsys" -a "$TEST_TYPE" == "" ]; then git remote -v; fi
  - if [ "$TRAVIS_BRANCH" == "gendoc" -a "$TEST_PACKAGE" == "hrpsys" -a "$TEST_TYPE" == "" ]; then git push --quiet https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git gh-pages; fi





